services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_USER=${GIT_USER}
      - GIT_TOKEN=${GIT_TOKEN}