services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_USER=${GIT_USER}
      - GIT_TOKEN=${GIT_TOKEN}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql

volumes:
  database: