services:
  mysql-local:
    container_name: mysql-local
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  projeto-integrado-vi:
    container_name: projeto-integrado-vi
    ports:
      - "8080:8080"  
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_data:/${GIT_REPO_NAME}
    environment:
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_USER=${GIT_USER}
      - GIT_TOKEN=${GIT_TOKEN}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - mysql-local
volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local