services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USER: ${GIT_USER}
        GIT_TOKEN: ${GIT_TOKEN}
        GIT_BRANCH: ${GIT_BRANCH}
        GIT_REPO_NAME: ${GIT_REPO_NAME}
    depends_on:
      - mysql

volumes:
  mysql_data: