openapi: 3.0.0
info:
  title: PUCC - Projeto Integrador VI
  description: API para gerenciamento de investimentos e portfólio.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor Local

paths:
  /login:
    post:
      summary: Login de usuário
      description: Autenticar um usuário no sistema.
      requestBody:
        description: Credenciais do usuário.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas

  /portfolio:
    get:
      summary: Obter portfólio de investimentos
      description: Retornar detalhes do portfólio do usuário, incluindo saldo, poder de compra, gráficos e ações.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Detalhes do portfólio retornados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountBalance:
                    type: number
                    description: Saldo da conta do usuário
                  graphData:
                    type: array
                    description: Dados para renderização do gráfico
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        value:
                          type: number
                  buyingPower:
                    type: number
                    description: Poder de compra disponível
                  interestAccruedThisMonth:
                    type: number
                    description: Juros acumulados no mês
                  lifetimeInterestPaid:
                    type: number
                    description: Total de juros pagos até agora
                  stocks:
                    type: array
                    description: Ações no portfólio do usuário
                    items:
                      type: object
                      properties:
                        ticker:
                          type: string
                        price:
                          type: number
                        quantity:
                          type: number
        '401':
          description: Não autorizado
        '500':
          description: Erro no servidor

  /stocks/search:
    get:
      summary: Buscar ações por nome ou símbolo
      description: Retornar lista de ações disponíveis para busca.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: Nome ou símbolo da ação.
      responses:
        '200':
          description: Ações retornadas com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ticker:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
        '404':
          description: Nenhuma ação encontrada

  /stocks/{stockId}/details:
    get:
      summary: Obter detalhes de uma ação
      description: Retornar detalhes sobre uma ação específica, incluindo preço, mudanças, gráficos, informações da empresa e estatísticas.
      parameters:
        - in: path
          name: stockId
          schema:
            type: string
          required: true
          description: 'Identificador da ação.'
      responses:
        '200':
          description: Detalhes da ação retornados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticker:
                    type: string
                    description: Símbolo da ação
                  price:
                    type: number
                    description: Preço atual da ação
                  change:
                    type: string
                    description: 'Mudança de preço (exemplo: +2%)'
                  graphData:
                    type: array
                    description: Dados para renderização do gráfico de variação de preço
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        value:
                          type: number
                  about:
                    type: object
                    description: Informações sobre a empresa
                    properties:
                      description:
                        type: string
                        description: Descrição da empresa
                      CEO:
                        type: string
                      founded:
                        type: string
                      employees:
                        type: string
                      headquarters:
                        type: string
                  stats:
                    type: object
                    description: Estatísticas da ação
                    properties:
                      open:
                        type: number
                      high:
                        type: number
                      low:
                        type: number
                      marketCap:
                        type: string
                      volume:
                        type: string
                      dividendYield:
                        type: string
                  news:
                    type: array
                    description: Notícias relacionadas à ação
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        source:
                          type: string
                        url:
                          type: string
        '404':
          description: Ação não encontrada

  /investment:
    post:
      summary: Adicionar novo investimento
      description: Adicionar uma nova ação ou ETF ao portfólio do usuário.
      security:
        - bearerAuth: []
      requestBody:
        description: Dados do investimento
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ticker:
                  type: string
                quantity:
                  type: number
                price:
                  type: number
              required:
                - ticker
                - quantity
                - price
      responses:
        '201':
          description: Investimento adicionado com sucesso
        '400':
          description: Dados inválidos
          
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
