openapi: 3.0.0
info:
  title: PUCC - Projeto Integrador VI
  description: API para gerenciamento de investimentos.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor Local
tags:
  - name: Auths
    description: Autenticação e Autorização de usuários
  - name: Usuários
    description: Operações referentes aos usuários
  - name: Em definição
    description: Recursos e campos em discussão
security:
  - basicAuth: []
paths:
  /auth/login:
    get:
      tags: 
        - Auths
      summary: Login de usuário
      description: Autenticar um usuário no sistema.
      responses:
        '200':
          description: Login bem-sucedido
          content:
            text/plain:
              schema:
                type: string
                description: User, Successfully logged in!
                example: "User, Successfully logged in!"
        '401':
          description: Credenciais inválidas
  /user:
    get:
      tags:
        - Usuários
      summary: Lista usuários
      description: Retorna os usuários cadastrados
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                      
        '400':
          description: Invalid ID supplied
        '401':
          description: Credenciais inválidasaa
    post:
      tags: 
        - Usuários
      summary: Cria um novo usuário
      description: Adiciona um novo usuário ao sistema
      requestBody:
        description: Dados do usuário
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - login
                - password
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                login:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuário adicionado com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Credenciais inválidas
  /user/{login}:
    get:
      tags:
        - Usuários
      summary: Lista dados do usuário
      description: Retorna as propriedades do usuario cadastradas
      parameters:
        - name: login
          in: path
          description: Login do usuario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  return:
                    $ref: '#/components/schemas/Result'
                      
        '400':
          description: Invalid ID supplied
        '401':
          description: Credenciais inválidasaa
  /portfolio:
    get:
      tags: 
        - Em definição
      summary: Obter portfólio de investimentos
      description: Retornar detalhes do portfólio do usuário, incluindo saldo, poder de compra, gráficos e ações.
      responses:
        '200':
          description: Detalhes do portfólio retornados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountBalance:
                    type: number
                    description: Saldo da conta do usuário
                  graphData:
                    type: array
                    description: Dados para renderização do gráfico
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        value:
                          type: number
                  buyingPower:
                    type: number
                    description: Poder de compra disponível
                  interestAccruedThisMonth:
                    type: number
                    description: Juros acumulados no mês
                  lifetimeInterestPaid:
                    type: number
                    description: Total de juros pagos até agora
                  stocks:
                    type: array
                    description: Ações no portfólio do usuário
                    items:
                      type: object
                      properties:
                        ticker:
                          type: string
                        price:
                          type: number
                        quantity:
                          type: number
                  return:
                    $ref: '#/components/schemas/Result'
        '401':
          description: Não autorizado
        '500':
          description: Erro no servidor
  /stocks/search:
    get:
      tags: 
        - Em definição
      summary: Buscar ações por nome ou símbolo
      description: Retornar lista de ações disponíveis para busca.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: Nome ou símbolo da ação.
      responses:
        '200':
          description: Ações retornadas com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ticker:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
        '404':
          description: Nenhuma ação encontrada
  /investment:
    post:
      tags: 
        - Em definição
      summary: Adicionar novo investimento
      description: Adicionar uma nova ação ou ETF ao portfólio do usuário.
      requestBody:
        description: Dados do investimento
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ticker:
                  type: string
                quantity:
                  type: number
                price:
                  type: number
              required:
                - ticker
                - quantity
                - price
      responses:
        '201':
          description: Investimento adicionado com sucesso
        '400':
          description: Dados inválidos
  /stocks/{ticker}:
    get:
      tags: 
        - Em definição
      summary: Obter detalhes de uma ação
      description: Retornar detalhes sobre uma ação específica, incluindo preço, mudanças, gráficos, informações da empresa e estatísticas.
      parameters:
        - in: path
          name: ticker
          schema:
            type: string
          required: true
          description: 'Símbolo da ação (exemplo: AMZN para Amazon).'
      responses:
        '200':
          description: Detalhes da ação retornados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticker:
                    type: string
                    description: Símbolo da ação
                  price:
                    type: number
                    description: Preço atual da ação
                  change:
                    type: string
                    description: 'Mudança de preço (exemplo: +2%)'
                  graphData:
                    type: array
                    description: Dados para renderização do gráfico de variação de preço
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        value:
                          type: number
                  about:
                    type: object
                    description: Informações sobre a empresa
                    properties:
                      description:
                        type: string
                        description: Descrição da empresa
                      CEO:
                        type: string
                      founded:
                        type: string
                      employees:
                        type: string
                      headquarters:
                        type: string
                  stats:
                    type: object
                    description: Estatísticas da ação
                    properties:
                      open:
                        type: number
                      high:
                        type: number
                      low:
                        type: number
                      marketCap:
                        type: string
                      volume:
                        type: string
                      dividendYield:
                        type: string
                  news:
                    type: array
                    description: Notícias relacionadas à ação
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        source:
                          type: string
                        url:
                          type: string
        '404':
          description: Ação não encontrada
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstName:
          type: string
        lastName:
          type: string
        access:
          type: object
          properties:
            login:
              type: string
            enabled:
              type: boolean
            roles:
              type: array
              items:
                properties:
                  role:
                    type: string
                  description:
                    type: string
    Result:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic